### ISSUE TITLE
Epiphany has outdated version

### ISSUE THREAD

**Issue by png2378** [alexlarsson/gnome-apps-nightly#35]
I installed GNOME Nightly repositories by following instructions from [Flatpak website](http://flatpak.org/apps.html) and try to install Epiphany nightly using `flatpak install gnome-nightly-apps org.gnome.Epiphany`. Apparently it should be [3.23.4](https://github.com/GNOME/epiphany/commit/acfe39787a2891d3411d3d665b625d2ce2cf94d2) version, but but in fact it is 3.21.2 version:

![](http://storage4.static.itmages.ru/i/17/0119/h_1484860524_5801115_36fd736c96.png)

I don't have any other installed runtimes or apps in my system. I use elementary OS 0.4 (based on Ubuntu 16.04), Flatpak was installed from `ppa:alexlarsson/flatpak`.

**Comment by alexlarsson** [comment]
There have been some changes in gnome master that caused the builds to fail recently, i guess this is what is causing this.

**Comment by png2378** [comment]
@alexlarsson, solution of this issue is included in your plans? Using the current nightly builds in Flatpak would be useful for many users.

**Comment by alexlarsson** [comment]
Yeah, it'll get fixed eventually.

**Comment by alexlarsson** [comment]
I believe this will fix it: 
https://git.gnome.org/browse/gnome-apps-nightly/commit/?id=1322d9908c980bfbadead7283f2f299e12b3cc8e

**Comment by alexlarsson** [comment]
built now

**Comment by png2378** [comment]
@alexlarsson for some reason locales are not updated, could you look at this?
