### ISSUE TITLE
GNOME Builder does not recognize the existence of files from other partitions

### ISSUE THREAD

**Issue by fusion809** [alexlarsson/gnome-apps-nightly#36]
Hi,

I've noticed that GNOME Builder seems to ignore the existence of files from mounted partitions other than my root partition. For example I mount `/dev/sda1` on `/data` and symlink `/data/Documents` on `~/Documents` and when I run:

```bash
flatpak run org.gnome.Builder $HOME/Documents/CodeLite/CPP-Math-Projects/Lorenz-equations-mysolver/
```

I get the error message:

```bash
11:01:02.0168                                    (null)[2]:  WARNING: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
11:01:10.0330                                  GLib-GIO[11]: CRITICAL: g_file_enumerator_next_file: assertion 'G_IS_FILE_ENUMERATOR (enumerator)' failed
11:01:10.0386                      ide-application-open[2]:  WARNING: Error when getting information for file “/home/fusion809/Documents/CodeLite/CPP-Math-Projects/Lorenz-equations-mysolver”: No such file or directory
```

I get the exact same error when I take the symlink out of the equation and run:

```bash
flatpak run org.gnome.Builder /data/Documents/CodeLite/CPP-Math-Projects/Lorenz-equations-mysolver/
```

To be clear I installed GNOME Builder by following the Flatpak Applications article (i.e., http://flatpak.org/apps), namely running:

```bash
flatpak install --from "https://git.gnome.org/browse/gnome-apps-nightly/plain/gnome-builder.flatpakref?h=gnome-3-22" --user
```

Thanks for your time,
Brenton

**Comment by alexlarsson** [comment]
@chergert seems you're only doing --filesystem=home

@fusion809 You can try `flatpak run --filesystem=host org.gnome.Buidler` which should let you get this.

**Comment by chergert** [comment]
Stable branch of Builder has been updated, should land in an upcoming build.

**Comment by fusion809** [comment]
@alexlarsson Thanks, worked!

**Comment by fusion809** [comment]
Oh one last thing, is there any place you can suggest I ask for further support with GNOME Builder? I've tried the #gnome channel on Freenode. As there's only 200 people in it and it's a general GNOME channel I don't expect that great of support.

**Comment by chergert** [comment]
We're in `#gnome-builder` on irc.gnome.org.

**Comment by fusion809** [comment]
Oh great. Rofl, just assumed freenode would be the place. Thanks.

**Comment by fusion809** [comment]
Turns out what I was asking about was a bug too. https://bugzilla.gnome.org/show_bug.cgi?id=780499. Mentioning as it might be relevant to Flatpak as it was this nightly Flatpak I was using when I got this bug.

**Comment by fusion809** [comment]
@alexlarsson I wouldn't suppose you's could bump the GNOME Builder nightly Flatpak for this latest commit https://git.gnome.org/browse/gnome-builder/commit/?id=100c5e6? I ask as this commit fixes the issue I reported in the above Bugzilla report.
